line-length = 79
extend-include = ["powa-web", "powa/powa.wsgi"]

[lint]
# Default `select` is: "E4", "E7", "E9", "F"
# `E` for "pycodestyle" (subset)
# `F` for "Pyflakes"

# In addition, we also enable:
# `Q` for "flake8-quotes"
# `I` for "isort"
# `UP` for "pyupgrade"
extend-select = ["Q", "I", "UP"]

[lint.per-file-ignores]
"powa/__init__.py" = ["E402"]

[lint.isort]
no-sections = true
