name: Trigger build and push of powa-web-git image

on:
  push:
    branches: [master]

env:
  TARGET_REPO: "powa-podman"
  EVENT_TYPE: "powa-web-git"

jobs:
  trigger_build:
    name: Trigger build and push of powa-web-git in powa-podman repo
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the powa-web-git repository dispatch
        run: |
          # Set variables
          org="${{ github.repository_owner }}"
          repo="${{ env.TARGET_REPO }}"
          event_type="${{ env.EVENT_TYPE }}"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${org}/${repo}/dispatches \
            -d "{\"event_type\": \"${event_type}\"}"
